name: Run Postman Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Newman Tests
        uses: matt-ball/newman-action@v2.0.0
        with:
          collection: path/to/your-collection.postman_collection.json
          environment: path/to/your-environment.postman_environment.json
          reporters: cli, junit
          reporter-options: junit-export=results.xml

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: postman-results
          path: results.xml
